[package]
name = "hermit-liteinst-runtime-artifact"
version = "0.2.0"
edition = "2024"
publish = false

[dependencies]
reverie-liteinst = { version = "0.2.0", git = "https://github.com/rrnewton/reverie.git", rev = "547278b9b5e9a205c92e40c9e6f189beb8a3ddd7", default-features = false, features = ["preload-constructor"] }
