[package]
name = "hermit-liteinst-runtime-artifact"
version = "0.2.0"
edition = "2024"
publish = false

[dependencies]
reverie-liteinst = { version = "0.2.0", git = "https://github.com/rrnewton/reverie.git", rev = "f6a7e7248f0415fe88284cae3e38a317571c288f", default-features = false, features = ["preload-constructor"] }
