[package]
name = "detcore-dbi"
version = "0.0.0"
edition = "2024"
license = "BSD-3-Clause"
repository = "https://github.com/facebookexperimental/hermit"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
detcore = { version = "0.0.0", path = "../detcore" }
libc = "0.2.186"
reverie = { version = "0.1.0", git = "https://github.com/rrnewton/reverie.git", rev = "1d5378a5a66e76cbd5af847366285a46f433d9c4" }
reverie-dbi = { version = "0.1.0", git = "https://github.com/rrnewton/reverie.git", rev = "1d5378a5a66e76cbd5af847366285a46f433d9c4", default-features = false }
serde_json = { version = "1.0.140", features = ["alloc", "float_roundtrip", "raw_value", "unbounded_depth"] }
