/*  Copyright © 2019 Software Reliability Group, Imperial College London
 *
 *  This file is part of SaBRe.
 *
 *  SPDX-License-Identifier: GPL-3.0-or-later
 */

/*
 * RUN: %{gcc} %s -o %t1
 * RUN: echo "Hello World!" > %t2
 * RUN: %{sbrtrace} %t1 &> %t3
 * RUN: diff %t2 %t3
 */

// #############################################################################
// # This file is autogenerated, do not edit!
// #############################################################################

#include <stdio.h>

int main(int argc, char *argv[]) {
  printf("Hello World!\n");
  return 0;
}
