[package]
name = "hermit-install"
version = "0.0.0"
edition = "2024"
license = "BSD-3-Clause"
repository = "https://github.com/facebookexperimental/hermit"
publish = false

[lib]
path = "src/lib.rs"

[build-dependencies]
reverie-dbi = { version = "0.1.0", git = "https://github.com/rrnewton/reverie.git", rev = "ce49a08ca03b54c28b6cae13b7b2eb3524a7651b", default-features = false }
