[package]
name = "hermit-install"
version = "0.0.0"
edition = "2024"
license = "BSD-3-Clause"
repository = "https://github.com/facebookexperimental/hermit"
publish = false

[lib]
path = "src/lib.rs"

[build-dependencies]
reverie-dbi = { version = "0.2.0", git = "https://github.com/rrnewton/reverie.git", rev = "a730afe13c4b64b90f052d73e7396763bfce5965", default-features = false }
