[package]
name = "hermit-install"
version = "0.2.0"
edition = "2024"
license = "BSD-3-Clause"
repository = "https://github.com/facebookexperimental/hermit"
publish = false

[lib]
path = "src/lib.rs"

[build-dependencies]
reverie-dbt = { version = "0.2.0", git = "https://github.com/rrnewton/reverie.git", rev = "3bf292b269daa85b6e3b01ef4f435dc89ea0df30", default-features = false }
