load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("hermit")

rust_library(
    name = "detcore-model",
    autocargo = {
        "cargo_toml_dir": ".",
        "cargo_toml_config": {
            "package": {
                "version": "0.4.1",
                "readme": "README.md",
                "homepage": "https://hermetic-infra.org",
                "documentation": "https://docs.rs/detcore-model",
                "keywords": [
                    "linux",
                    "hermit",
                    "determinism",
                    "debugging"
                ],
                "categories": [
                    "development-tools::debugging",
                    "development-tools::testing"
                ]
            },
        },
    },
    srcs = glob(["src/**/*"]),
    test_deps = [
        "fbsource//third-party/rust:pretty_assertions",
    ],
    deps = [
        "fbsource//third-party/rust:anyhow",
        "fbsource//third-party/rust:bincode",
        "fbsource//third-party/rust:serde_json",
        "fbsource//third-party/rust:bitvec",
        "fbsource//third-party/rust:bytesize",
        "fbsource//third-party/rust:chrono",
        "fbsource//third-party/rust:clap",
        "fbsource//third-party/rust:libc",
        "fbsource//third-party/rust:nix",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:shell-words",
        "fbsource//third-party/rust:tracing",
        "//hermetic_infra/reverie:reverie",
        "//hermetic_infra/reverie:reverie-syscalls",
    ],
)
