[workspace]
resolver = "3"

[package]
name = "hermit-liteinst-runtime-build"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
crate-type = ["rlib"]

[build-dependencies]
goblin = "0.10.7"
reverie-liteinst = { version = "0.1.0", git = "https://github.com/rrnewton/reverie.git", rev = "87aa36f9d3ffab13ad34cce1e7ca958923185d78", default-features = false, features = ["preload-constructor"] }
