[package]
name = "detcore-liteinst"
version = "0.0.0"
edition = "2024"
license = "BSD-3-Clause"
repository = "https://github.com/facebookexperimental/hermit"

[lib]
crate-type = ["cdylib"]

[dependencies]
reverie-liteinst = { version = "0.1.0", git = "https://github.com/rrnewton/reverie.git", rev = "1e58dd6503a81101a49149a0de5ff1f68439767f", default-features = false }
