[package]
name = "hermit-plugin-protocol"
description = "Versioned control protocol for optional Hermit execution plugins."
version = "0.2.0"
edition = "2024"
repository = "https://github.com/facebookexperimental/hermit"
license = "BSD-3-Clause"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
