load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("hermit")

rust_library(
    name = "hermit-resources",
    srcs = glob(["src/**/*.rs"]),
    autocargo = {
        "cargo_toml_dir": ".",
        "cargo_toml_config": {
            "package": {
                "version": "0.4.1",
                "readme": "README.md",
                "homepage": "https://hermetic-infra.org",
                "documentation": "https://docs.rs/hermit-resources",
                "keywords": [
                    "linux",
                    "hermit",
                    "determinism",
                    "debugging"
                ],
                "categories": [
                    "development-tools::debugging",
                    "development-tools::testing"
                ]
            },
        },
    },
)
