load("@fbsource//tools/build_defs:rust_library.bzl", "rust_library")

oncall("hermit")

rust_library(
    name = "digest",
    srcs = glob(["digest/src/**/*.rs"]),
    autocargo = {"cargo_toml_dir": "digest"},
    deps = [
        "fbsource//third-party/rust:hex",
        "fbsource//third-party/rust:serde",
        "fbsource//third-party/rust:sha2",
    ],
)

rust_library(
    name = "edit-distance",
    srcs = glob(["edit-distance/src/**/*"]),
    autocargo = {"cargo_toml_dir": "edit-distance"},
    test_deps = [
        "fbsource//third-party/rust:rand",
        "fbsource//third-party/rust:serde_json",
    ],
    deps = [
        "fbsource//third-party/rust:serde",
    ],
)
