[package]
name = "detcore-sabre"
description = "SaBRe backend glue for Detcore, the Hermit deterministic execution engine."
version = "0.2.0"
edition = "2024"
license = "BSD-3-Clause"
repository = "https://github.com/facebookexperimental/hermit"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
detcore = { version = "0.2.0", path = "../detcore" }
libc = "0.2.186"
reverie = { package = "reverie-core", version = "0.2.0", git = "https://github.com/rrnewton/reverie.git", rev = "774fdb68f9e5476fb4f70e7028613f3d2f13d754" }
reverie-memory = { version = "0.2.0", git = "https://github.com/rrnewton/reverie.git", rev = "774fdb68f9e5476fb4f70e7028613f3d2f13d754" }
reverie-rpc-transport = { version = "0.2.0", git = "https://github.com/rrnewton/reverie.git", rev = "774fdb68f9e5476fb4f70e7028613f3d2f13d754" }
reverie-sabre = { version = "0.2.0", git = "https://github.com/rrnewton/reverie.git", rev = "774fdb68f9e5476fb4f70e7028613f3d2f13d754" }
reverie-syscalls = { version = "0.2.0", git = "https://github.com/rrnewton/reverie.git", rev = "774fdb68f9e5476fb4f70e7028613f3d2f13d754" }
syscalls = { version = "0.6.7", features = ["serde"] }
