[package]
name = "detcore-sabre"
description = "SaBRe backend glue for Detcore, the Hermit deterministic execution engine."
version = "0.4.0"
edition = "2024"
license = "BSD-3-Clause"
repository = "https://github.com/facebookexperimental/hermit"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
detcore = { package = "hermit-detcore", version = "0.4.0", path = "../detcore" }
libc = "0.2.186"
reverie = { package = "reverie-core", version = "0.4.1", git = "https://github.com/rrnewton/reverie.git", rev = "589ee25275ff6670b57da5f692fb2a6ceea63cba" }
reverie-memory = { version = "0.4.1", git = "https://github.com/rrnewton/reverie.git", rev = "589ee25275ff6670b57da5f692fb2a6ceea63cba" }
reverie-rpc-transport = { version = "0.4.1", git = "https://github.com/rrnewton/reverie.git", rev = "589ee25275ff6670b57da5f692fb2a6ceea63cba" }
reverie-sabre = { version = "0.4.0", git = "https://github.com/rrnewton/reverie.git", rev = "589ee25275ff6670b57da5f692fb2a6ceea63cba" }
reverie-syscalls = { version = "0.4.1", git = "https://github.com/rrnewton/reverie.git", rev = "589ee25275ff6670b57da5f692fb2a6ceea63cba" }
syscalls = { version = "0.6.7", features = ["serde"] }
