[package]
name = "detcore-sabre"
description = "SaBRe backend glue for Detcore, the Hermit deterministic execution engine."
version = "0.4.0"
edition = "2024"
license = "BSD-3-Clause"
repository = "https://github.com/facebookexperimental/hermit"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
detcore = { package = "hermit-detcore", version = "0.4.0", path = "../detcore" }
libc = "0.2.186"
reverie = { package = "reverie-core", version = "0.4.1", git = "https://github.com/rrnewton/reverie.git", rev = "c8181d43a59a6d1ac602f2fad7615189f4996b41" }
reverie-memory = { version = "0.4.1", git = "https://github.com/rrnewton/reverie.git", rev = "c8181d43a59a6d1ac602f2fad7615189f4996b41" }
reverie-rpc-transport = { version = "0.4.1", git = "https://github.com/rrnewton/reverie.git", rev = "c8181d43a59a6d1ac602f2fad7615189f4996b41" }
reverie-sabre = { version = "0.4.0", git = "https://github.com/rrnewton/reverie.git", rev = "c8181d43a59a6d1ac602f2fad7615189f4996b41" }
reverie-syscalls = { version = "0.4.1", git = "https://github.com/rrnewton/reverie.git", rev = "c8181d43a59a6d1ac602f2fad7615189f4996b41" }
syscalls = { version = "0.6.7", features = ["serde"] }
