"""Typed subset of LLDB's Python API used by the debugger integration tests."""

LLDB_INVALID_ADDRESS: int
eStateExited: int


class SBListener: ...


class SBModule: ...


class SBError:
    def Success(self) -> bool: ...
    def GetCString(self) -> str | None: ...


class SBAddress:
    def GetLoadAddress(self, target: SBTarget) -> int: ...


class SBBreakpointLocation:
    def GetAddress(self) -> SBAddress: ...


class SBBreakpoint:
    def GetNumLocations(self) -> int: ...
    def GetLocationAtIndex(self, index: int) -> SBBreakpointLocation: ...


class SBValue:
    def GetValue(self) -> str | None: ...


class SBFrame:
    def GetFunctionName(self) -> str | None: ...
    def FindVariable(self, name: str) -> SBValue: ...


class SBThread:
    def GetNumFrames(self) -> int: ...
    def GetFrameAtIndex(self, index: int) -> SBFrame: ...
    def StepOver(self) -> None: ...


class SBProcess:
    def IsValid(self) -> bool: ...
    def Kill(self) -> None: ...
    def Continue(self) -> None: ...
    def GetSelectedThread(self) -> SBThread: ...
    def GetState(self) -> int: ...
    def GetExitStatus(self) -> int: ...


class SBTarget:
    def IsValid(self) -> bool: ...
    def ConnectRemote(
        self,
        listener: SBListener,
        url: str,
        plugin_name: str,
        error: SBError,
    ) -> SBProcess: ...
    def GetModuleAtIndex(self, index: int) -> SBModule: ...
    def SetModuleLoadAddress(self, module: SBModule, slide: int) -> SBError: ...
    def BreakpointCreateByName(self, name: str) -> SBBreakpoint: ...


class SBDebugger:
    @staticmethod
    def Create() -> SBDebugger: ...
    @staticmethod
    def Destroy(debugger: SBDebugger) -> None: ...
    def SetAsync(self, is_async: bool) -> None: ...
    def CreateTarget(self, filename: str) -> SBTarget: ...
    def GetListener(self) -> SBListener: ...
