#!/usr/bin/env bash
# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
# check-detcore-nostd.sh
# ----------------------
# Check Detcore and detcore-model without std, for the Narf kernel target
# (x86_64-unknown-none), and count the compile errors per crate.
#
# On `target_os = "none"`, Detcore and detcore-model are `#![no_std]`: they
# bind detcore-std as `std` and detcore-libc as `libc` (and detcore-model
# binds detcore-clap as `clap`), and leave out what needs an operating
# system. This script type-checks that configuration. The
# port is not finished, so it is a progress measure, not a CI gate.
#
# usage: scripts/check-detcore-nostd.sh --reverie PATH [--toolchain NAME]
#
# PATH is a Reverie checkout whose reverie-core builds without std. Detcore's
# pinned Reverie (dbf2b5c8) does not yet; the no-std port is the branch
# sub-narf-opus/m3-lifecycle-wait of https://github.com/rrnewton/reverie.
#
# NAME is the rustup toolchain, by default nightly-2025-09-14, the one Narf
# builds with. It needs the x86_64-unknown-none target and rust-src, which
# hermit's own toolchain (rust-toolchain.toml) does not have.
#
# How: detcore/Cargo.toml and detcore-model/Cargo.toml are generated by
# autocargo and describe the host build, whose dependencies need std. So the
# script writes a workspace under target/detcore-nostd with its own manifests
# for the two packages, built from their real sources. The manifests come from
# scripts/detcore-nostd-manifests.sh, which export-detcore-kernel-crates.sh
# shares and which says how they relate to the generated ones.
# It patches Detcore's Reverie git dependencies to PATH, seeds the lockfile
# from Cargo.lock, and runs `cargo check` offline for x86_64-unknown-none with
# -Zbuild-std=core,alloc and --keep-going. Run `cargo fetch` first if the
# registry lacks a crate.
#
# rand_pcg 0.10.2 asks for serde with its default features, which include
# std. The workspace patches in a copy of rand_pcg from the cargo registry
# with only that dependency changed to `default-features = false`.
#
# Output: errors and warnings per crate, and the crates cargo did not reach
# because a dependency failed. The compiler output is in
# target/detcore-nostd/check.log. rustc's counts are approximate: an
# unresolved import hides the errors behind it, so fixing one error can
# reveal others.
#
# Exit codes:
#   0  everything compiles
#   1  compile errors
#   2  usage / environment error

set -uo pipefail

usage() {
    echo "usage: $0 --reverie PATH [--toolchain NAME]"
}

reverie=""
toolchain=nightly-2025-09-14
while (($# > 0)); do
    case "$1" in
        --reverie | --toolchain)
            if (($# < 2)); then
                echo "error: $1 requires a value" >&2
                exit 2
            fi
            if [[ $1 == --reverie ]]; then reverie=$2; else toolchain=$2; fi
            shift 2
            ;;
        -h | --help)
            usage
            exit 0
            ;;
        *)
            echo "error: unknown argument: $1" >&2
            usage >&2
            exit 2
            ;;
    esac
done

if [[ -z $reverie ]]; then
    echo "error: --reverie PATH is required" >&2
    usage >&2
    exit 2
fi
if ! reverie="$(cd -- "$reverie" 2>/dev/null && pwd)"; then
    echo "error: --reverie: no such directory" >&2
    exit 2
fi
for crate in reverie reverie-process reverie-syscalls; do
    if [[ ! -f $reverie/$crate/Cargo.toml ]]; then
        echo "error: $reverie/$crate/Cargo.toml not found; is it a Reverie checkout?" >&2
        exit 2
    fi
done

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=scripts/detcore-nostd-manifests.sh
source "$REPO_ROOT/scripts/detcore-nostd-manifests.sh"
WS="$REPO_ROOT/target/detcore-nostd"
mkdir -p "$WS/src" "$WS/detcore" "$WS/detcore-model"

# rand_pcg with serde's default features off.
registry="${CARGO_HOME:-$HOME/.cargo}/registry"
pcg=rand_pcg-0.10.2
rm -rf "${WS:?}/$pcg"
pcg_src="$(ls -d "$registry"/src/*/"$pcg" 2>/dev/null | head -n 1)"
pcg_crate="$(ls "$registry"/cache/*/"$pcg.crate" 2>/dev/null | head -n 1)"
if [[ -n $pcg_src ]]; then
    cp -r "$pcg_src" "$WS/$pcg"
elif [[ -n $pcg_crate ]]; then
    tar -xzf "$pcg_crate" -C "$WS"
else
    echo "error: $pcg is not in $registry; run cargo fetch in $REPO_ROOT" >&2
    exit 2
fi
pcg_toml="$WS/$pcg/Cargo.toml"
sed -i '/^\[dependencies\.serde\]$/a default-features = false' "$pcg_toml"
if [[ $(grep -c -x '\[dependencies\.serde\]' "$pcg_toml") -ne 1 ]] ||
    [[ $(grep -A 1 -x '\[dependencies\.serde\]' "$pcg_toml" | tail -n 1) != 'default-features = false' ]]; then
    echo "error: $pcg's manifest is not the expected one; update this script" >&2
    exit 2
fi

reverie_git='git = "https://github.com/rrnewton/reverie.git", rev = "dbf2b5c8880bac5fd6a06fa1f296b3eec3590569"'

cat >"$WS/Cargo.toml" <<EOF
# Generated by scripts/check-detcore-nostd.sh; rewritten on every run.
[package]
name = "detcore-nostd-check"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
detcore = { package = "hermit-detcore", path = "detcore" }
detcore-model = { path = "detcore-model" }

[workspace]

[patch."https://github.com/rrnewton/reverie.git"]
reverie-core = { path = "$reverie/reverie" }
reverie-process = { path = "$reverie/reverie-process" }
reverie-syscalls = { path = "$reverie/reverie-syscalls" }

[patch.crates-io]
rand_pcg = { path = "$pcg" }
EOF

{
    echo "# Generated by scripts/check-detcore-nostd.sh; rewritten on every run."
    echo "# Detcore without std: see scripts/detcore-nostd-manifests.sh for how"
    echo "# this relates to detcore/Cargo.toml."
    detcore_nostd_manifest "$REPO_ROOT/detcore/src/lib.rs" "$REPO_ROOT/detcore-libc" \
        ../detcore-model "$REPO_ROOT/detcore-std" "$reverie_git"
} >"$WS/detcore/Cargo.toml"

{
    echo "# Generated by scripts/check-detcore-nostd.sh; rewritten on every run."
    echo "# detcore-model without std: see scripts/detcore-nostd-manifests.sh for"
    echo "# how this relates to detcore-model/Cargo.toml."
    detcore_model_nostd_manifest "$REPO_ROOT/detcore-model/src/lib.rs" \
        "$REPO_ROOT/detcore-clap" "$REPO_ROOT/detcore-libc" "$REPO_ROOT/detcore-std" \
        "$reverie_git"
} >"$WS/detcore-model/Cargo.toml"

cat >"$WS/src/lib.rs" <<'EOF'
#![no_std]
extern crate detcore;
extern crate detcore_model;
EOF
cp "$REPO_ROOT/Cargo.lock" "$WS/Cargo.lock"

log="$WS/check.log"
env -C "$WS" -u RUSTFLAGS -u CARGO_BUILD_TARGET CARGO_TARGET_DIR="$WS/target" \
    cargo "+$toolchain" check --lib --offline --keep-going --verbose \
    --target x86_64-unknown-none -Zbuild-std=core,alloc \
    --message-format=short >"$log" 2>&1
rc=$?

echo "toolchain: $(rustc "+$toolchain" --version 2>/dev/null || echo "$toolchain")"
echo "reverie:   $reverie ($(git -C "$reverie" rev-parse --short=12 HEAD 2>/dev/null || echo "not a git checkout"))"
total=0
for crate in detcore-std detcore-libc detcore-clap detcore-model hermit-detcore; do
    failed="$(sed -n -E "s/^error: could not compile \`$crate\` \(lib\) due to ([0-9]+) previous errors?.*/\\1/p" "$log")"
    warnings="$(sed -n -E \
        -e "s/^warning: \`$crate\` \(lib\) generated ([0-9]+) warnings?.*/\\1/p" \
        -e "s/^error: could not compile \`$crate\` .*; ([0-9]+) warnings? emitted.*/\\1/p" "$log" |
        head -n 1)"
    if [[ -n $failed ]]; then
        printf '%-15s %4s errors, %s warnings\n' "$crate" "$failed" "${warnings:-0}"
        total=$((total + failed))
    elif grep -q -E "^ +(Checking|Compiling|Fresh) $crate v" "$log"; then
        printf '%-15s    0 errors, %s warnings\n' "$crate" "${warnings:-0}"
    else
        printf '%-15s not reached (a dependency failed)\n' "$crate"
    fi
done
# Any other crate that failed: a dependency built without std.
others="$(grep -E '^error: could not compile `' "$log" |
    grep -v -E '`(detcore-std|detcore-libc|detcore-clap|detcore-model|hermit-detcore)`')"
if [[ -n $others ]]; then
    echo "$others"
fi
echo "total: $total errors in Detcore's crates (log: $log)"

if ((rc == 0)); then
    exit 0
fi
if ((total == 0)) && [[ -z $others ]]; then
    echo "error: cargo failed without a compile error; see $log" >&2
    exit 2
fi
exit 1
