# shellcheck shell=bash
# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.
#
# detcore-nostd-manifests.sh
# --------------------------
# Sourced, not run: the Cargo manifests of Detcore and detcore-model without
# std, for the Narf kernel target, shared by check-detcore-nostd.sh and
# export-detcore-kernel-crates.sh.
#
# detcore/Cargo.toml and detcore-model/Cargo.toml are generated by autocargo
# and describe the host build, whose dependencies (tokio, nix, clap, the
# default features of serde and others) need std. These manifests take the
# same sources with the dependencies of the generated manifests that work
# without std, with their default features off, plus detcore-std,
# detcore-libc, detcore-clap and (for detcore-model's `Pid` and `Signal`)
# reverie-process. KEEP THEM IN STEP with the generated manifests: same
# versions, and no dependency the generated ones lack other than those four.
#
# Each function prints a manifest from `[package]` on; the caller writes its
# own header comment first. REVERIE_GIT is the git source of the Reverie
# crates, as it appears in a dependency table, for example
#   git = "https://github.com/rrnewton/reverie.git", rev = "<commit>"

# usage: detcore_nostd_manifest LIB_RS DETCORE_LIBC DETCORE_MODEL DETCORE_STD REVERIE_GIT
# LIB_RS is detcore/src/lib.rs; the others are package directories.
detcore_nostd_manifest() {
    cat <<EOF
[package]
name = "hermit-detcore"
version = "0.2.0"
edition = "2024"
publish = false

[lib]
name = "detcore"
path = "$1"

[dependencies]
anyhow = { version = "1.0.103", default-features = false }
async-trait = "0.1.86"
bitflags = { version = "2.13.1", features = ["serde"], default-features = false }
chrono = { version = "0.4.45", features = ["alloc", "serde"], default-features = false }
detcore-libc = { version = "0.2.0", path = "$2" }
detcore-model = { version = "0.2.0", path = "$3" }
detcore-std = { version = "0.2.0", path = "$4" }
futures = { version = "0.3.31", features = ["alloc", "async-await"], default-features = false }
hex = { version = "0.4.3", features = ["alloc"], default-features = false }
rand = { version = "0.10.2", features = ["alloc"], default-features = false }
rand_distr = { version = "0.6", features = ["alloc"], default-features = false }
rand_pcg = { version = "0.10.2", features = ["serde"] }
raw-cpuid = "10.7.0"
regex = { version = "1.13.1", features = ["unicode"], default-features = false }
reverie = { package = "reverie-core", version = "0.2.0", $5, default-features = false }
serde = { version = "1.0.219", features = ["alloc", "derive", "rc"], default-features = false }
serde_json = { version = "1.0.140", features = ["alloc", "float_roundtrip", "raw_value", "unbounded_depth"], default-features = false }
sha2 = { version = "0.10.6", default-features = false }
tracing = { version = "0.1.41", features = ["attributes", "valuable"], default-features = false }
EOF
}

# usage: detcore_model_nostd_manifest LIB_RS DETCORE_CLAP DETCORE_LIBC DETCORE_STD REVERIE_GIT
# LIB_RS is detcore-model/src/lib.rs; the others are package directories.
detcore_model_nostd_manifest() {
    cat <<EOF
[package]
name = "detcore-model"
version = "0.2.0"
edition = "2024"
publish = false

[lib]
path = "$1"

[dependencies]
anyhow = { version = "1.0.103", default-features = false }
bincode = { version = "2", features = ["alloc", "serde"], default-features = false }
bitvec = { version = "1.1.1", features = ["alloc", "atomic", "serde"], default-features = false }
bytesize = { version = "2.4.2", default-features = false }
chrono = { version = "0.4.45", features = ["alloc", "serde"], default-features = false }
detcore-clap = { version = "0.2.0", path = "$2" }
detcore-libc = { version = "0.2.0", path = "$3" }
detcore-std = { version = "0.2.0", path = "$4" }
reverie-process = { version = "0.2.0", $5, default-features = false }
reverie-syscalls = { version = "0.2.0", $5, default-features = false }
serde = { version = "1.0.219", features = ["alloc", "derive", "rc"], default-features = false }
serde_json = { version = "1.0.140", features = ["alloc", "float_roundtrip", "raw_value", "unbounded_depth"], default-features = false }
shell-words = { version = "1.1.1", default-features = false }
tracing = { version = "0.1.41", features = ["attributes", "valuable"], default-features = false }
EOF
}
