name: Rust

on:
  push:
    branches: [ "main", "integration" ]
  pull_request:
    branches: [ "main", "integration" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -C link-arg=-llzma

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: sudo apt-get install -y libunwind-dev liblzma-dev
    - name: Build
      run: cargo build

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: sudo apt-get install -y libunwind-dev liblzma-dev
    - name: Test
      run: cargo test --workspace

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: sudo apt-get install -y libunwind-dev liblzma-dev
    - name: Rust components
      run: rustup component add clippy
    - name: Clippy
      run: cargo clippy --all-targets -- -D warnings

  fmt:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Rust components
      run: rustup component add rustfmt
    - name: Format
      run: cargo fmt --check
